# Generated by Django 4.2.4 on 2023-10-14 10:36

import api
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('qtd_taloes', models.IntegerField(verbose_name='Quantidade de Talões')),
                ('qtd_cartela_talao', models.IntegerField(verbose_name='Quantidade de Cartela por Talão')),
                ('valor_venda_cartela', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor de Venda da Cartela')),
                ('valor_comissao_cartela', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Máximo da Comissão por Cartela')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='MeioPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Meio de Pagamento',
                'verbose_name_plural': 'Meios de Pagamento',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Talao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, verbose_name='Número')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Talão',
                'verbose_name_plural': 'Talões',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.AddField(
            model_name='evento',
            name='operadores',
            field=models.ManyToManyField(to='bingo.pessoa', verbose_name='Operadores'),
        ),
        migrations.CreateModel(
            name='Cartela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, verbose_name='Número')),
                ('realizou_pagamento', models.BooleanField(null=True, verbose_name='Realizou Pagamento')),
                ('comissao', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Comissão')),
                ('meio_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bingo.meiopagamento', verbose_name='Meio de Pagamento')),
                ('posse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possecartela_set', to='bingo.pessoa', verbose_name='Posse')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bingo.pessoa', verbose_name='Responsável')),
                ('talao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.talao', verbose_name='Talão')),
            ],
            options={
                'verbose_name': 'Cartega',
                'verbose_name_plural': 'Cartelas',
            },
            bases=(models.Model, api.ModelMixin),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            bases=(models.Model, api.ModelMixin),
        ),
    ]
