# Generated by Django 4.2.4 on 2023-10-18 19:53

import api
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone')),
                ('numero_cartelas', models.IntegerField(default=1, verbose_name='Número de Cartelas')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('uuid', models.CharField(max_length=100, verbose_name='UUID')),
                ('status', models.CharField(max_length=25, verbose_name='Status')),
                ('identifier', models.CharField(max_length=25, verbose_name='Identifier')),
                ('qrcode', models.TextField(verbose_name='QrCode')),
                ('url', models.CharField(max_length=25, verbose_name='URL')),
                ('cartelas', models.ManyToManyField(blank=True, to='bingo.cartela', verbose_name='Cartelas')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.evento')),
            ],
            options={
                'verbose_name': 'Compra Online',
                'verbose_name_plural': 'Compra Online',
            },
            bases=(models.Model, api.ModelMixin),
        ),
    ]
