# Generated by Django 4.2.4 on 2023-10-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_compraonline_data_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraonline',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='compraonline',
            name='numero_cartelas',
        ),
        migrations.RemoveField(
            model_name='compraonline',
            name='qrcode',
        ),
    ]
