# Generated by Django 4.2.4 on 2023-10-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_remove_compraonline_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraonline',
            name='numero_cartelas',
            field=models.IntegerField(default=1, verbose_name='Número de Cartelas'),
        ),
    ]
