# Generated by Django 4.2.4 on 2023-10-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0006_compraonline_numero_cartelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraonline',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
    ]
